// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBz-GbFqVpZsS98177J_b0a6NrJ_Gm7UZs',
    appId: '1:739934329938:web:117804e113cdb2ff73138b',
    messagingSenderId: '739934329938',
    projectId: 'team3chat-8b26c',
    authDomain: 'team3chat-8b26c.firebaseapp.com',
    storageBucket: 'team3chat-8b26c.firebasestorage.app',
    measurementId: 'G-HPVJ3PH5TG',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNLiWVSj_Sg78f_g8W_OdpJvyUEN7AGc',
    appId: '1:739934329938:ios:e9c44b6a7ea6d58b73138b',
    messagingSenderId: '739934329938',
    projectId: 'team3chat-8b26c',
    storageBucket: 'team3chat-8b26c.firebasestorage.app',
    iosBundleId: 'com.uprmonline.uprmChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeNLiWVSj_Sg78f_g8W_OdpJvyUEN7AGc',
    appId: '1:739934329938:ios:e9c44b6a7ea6d58b73138b',
    messagingSenderId: '739934329938',
    projectId: 'team3chat-8b26c',
    storageBucket: 'team3chat-8b26c.firebasestorage.app',
    iosBundleId: 'com.uprmonline.uprmChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBz-GbFqVpZsS98177J_b0a6NrJ_Gm7UZs',
    appId: '1:739934329938:web:1b5ed7e0f8f876cc73138b',
    messagingSenderId: '739934329938',
    projectId: 'team3chat-8b26c',
    authDomain: 'team3chat-8b26c.firebaseapp.com',
    storageBucket: 'team3chat-8b26c.firebasestorage.app',
    measurementId: 'G-EV48Z3ZTQB',
  );
}
